### ISSUE TITLE
Please Release Version: 1.5.3

### ISSUE THREAD

**Issue by cyrus07424** [webjars/leaflet-markercluster#2]
Please Release Version: [1.5.3](https://github.com/Leaflet/Leaflet.markercluster/releases/tag/v1.5.3)

**Comment by cyrus07424** [comment]
It looks not includes javascript files.
Could you build the javascript files and include them into webjars?
Thank you.

**Comment by jamesward** [comment]
The release doesn't include them:
https://github.com/Leaflet/Leaflet.markercluster/tree/master/dist

So it looks like something with their `1.5.3` release went wrong.  Can you file a bug with them?

**Comment by cyrus07424** [comment]
> Can you file a bug with them?

I see. I report this to their repository.
And I will use npm version of this library instead.
Thank you.
